# Generated by scripts/audit_gog_qol.py; see docs/gog-qol.md.
function Assert-GogQolStock {
    param([byte[]]$Bytes)
    if ($Bytes.Length -lt 0x400) { return }
    $pe = [BitConverter]::ToUInt32($Bytes, 0x3C)
    if ($pe -gt ($Bytes.Length - 24) -or [BitConverter]::ToUInt32($Bytes, $pe + 8) -ne 0x5BBB8DB8) { return }
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        $table = $pe + 24 + [BitConverter]::ToUInt16($Bytes, $pe + 20)
        $header = [BitConverter]::ToString($sha.ComputeHash($Bytes,$table,160)).Replace('-','')
        if ($header -ne "2986FD63DAA2836FBE20521241446CDB718644BA9B1108D830B92FCED92A6DBF") { throw "GOG stock section layout differs. No files were changed." }
        $ranges = @(
            @(301254, 255, "615D19DD0CBC42826C37E2C3779A6FD2941AD858303239BA014A7178CD7E82A2"),
            @(203376, 243, "5CA99A13D25CAF8D61BB457742B70F14386D8FFF3875F33796377155EFA386E3")
        )
        foreach ($range in $ranges) {
            $actual = [BitConverter]::ToString($sha.ComputeHash($Bytes,$range[0],$range[1])).Replace('-','')
            if ($actual -ne $range[2]) { throw "GOG stock QoL lifecycle bytes differ. No files were changed." }
        }
    } finally { $sha.Dispose() }
}
