#pragma once
#include "GogAuditedRanges.h"

// Generated by scripts/audit_gog_quests.py; see docs/gog-workshop-quests.md.
namespace MajestyGogAudit {
constexpr Range kWorkshopQuests[] = {
    {0x000EFCBB, 54, 0x8AAD89BDu, 0, 0}, // last local quest scan and finalize boundary
    {0x00119650, 612, 0x323303FBu, 0, 0}, // recursive quest directory scanner
    {0x001195A0, 166, 0xCE487C09u, 0, 0}, // quest manifest XML load and release
    {0x00119520, 128, 0x4B8C414Au, 0, 0}, // Quest node iteration
    {0x00119380, 403, 0x753FCE1Fu, 0, 0}, // Quest registration and native duplicate handling
    {0x00117F60, 172, 0x526800E8u, 0, 0}, // quest lookup by native GUID key
    {0x00136B10, 182, 0xD772D17Eu, 0, 0}, // native GUID key mapping
    {0x00113860, 180, 0xCF7E171Au, 0, 0}, // Quest construction using stock Mod initialization
    {0x00136C20, 298, 0xA801A6C9u, 0, 0}, // GUID storage and XML document retention
    {0x00113A30, 72, 0xFC67EB68u, 0, 0}, // Quest destruction
    {0x00135CE0, 119, 0x4CC980A2u, 0, 0}, // base Mod destruction and XML release
    {0x00118100, 50, 0x33340D66u, 0, 0}, // quest list insertion
    {0x001163C0, 168, 0x707EE74Fu, 0, 0}, // quest list node construction
    {0x0011A940, 108, 0xF24949DDu, 0, 0}, // quest list sentinel initialization
    {0x0011A9B0, 105, 0xF99E0BEBu, 0, 0}, // quest list destruction
    {0x0011CD90, 273, 0xF34F87E0u, 0, 0}, // quest manager destruction
    {0x0011CEB0, 1348, 0x4901AD19u, 0, 0}, // quest manager construction
    {0x0011D400, 111, 0x10A1B92Fu, 0, 0}, // quest manager lazy creation
    {0x0011DC90, 39, 0x41415D2Eu, 0, 0}, // quest manager destruction and owner clear
    {0x000EF027, 5, 0x40B58505u, 0, 0}, // stock resource teardown calls quest cleanup
    {0x000F9DA0, 275, 0x81FF5494u, 0, 0}, // XML manifest-relative resource directory
    {0x00286530, 301, 0x55DDD320u, 0, 0}, // native GUID parsing
    {0x002864B0, 128, 0xE682F849u, 0, 0}, // native GUID hex parser
    {0x0023C370, 69, 0x22529BDFu, 0, 0}, // stock string construction
    {0x0023C520, 33, 0x788DA9A2u, 0, 0}, // stock string destruction
};
} // namespace MajestyGogAudit
