#pragma once
#include "GogAuditedRanges.h"

// Generated by scripts/audit_gog_standard_mods.py; see docs/gog-standard-mods.md.
namespace MajestyGogAudit {
constexpr Range kStandardMods[] = {
    {0x000EFCF1, 43, 0xEAE5B8A2u, 0, 0}, // startup scan arguments and call
    {0x00139890, 611, 0x91003D32u, 0, 0}, // recursive directory scan
    {0x001397E0, 161, 0xFC507074u, 0, 0}, // manifest XML load and registration
    {0x00139760, 115, 0xA9C6AAAEu, 0, 0}, // Mod node iteration
    {0x00139590, 464, 0x2E689754u, 0, 0}, // Mod registration and installed-list insertion
    {0x000F9DA0, 275, 0x81FF5494u, 0, 0}, // XML manifest path and relative directory ownership
    {0x00136E70, 173, 0x69CE5E6Au, 0, 0}, // Mod construction
    {0x00136C20, 298, 0xA801A6C9u, 0, 0}, // Mod initialization and XML retention
    {0x00135CE0, 119, 0x4CC980A2u, 0, 0}, // Mod destruction and XML release
    {0x00138370, 50, 0x1A0915D9u, 0, 0}, // installed-list append
    {0x00138EA0, 136, 0x426EC6C8u, 0, 0}, // installed-list GUID lookup
    {0x00138D90, 250, 0xD8A6FCB3u, 0, 0}, // stock installed and active list cleanup
    {0x000EF068, 10, 0xDF51C9F9u, 0, 0}, // resource teardown dispatch to mod cleanup
    {0x00349AA0, 22, 0x2C2E8587u, 0, 0}, // CRT installed-list initialization
    {0x0031CAB0, 10, 0x958EFF8Fu, 0, 0}, // CRT installed-list destruction
    {0x00136AA0, 108, 0xAC4B183Fu, 0, 0}, // list sentinel construction
    {0x001366E0, 89, 0x1D5B21FFu, 0, 0}, // list destruction
    {0x0035B1A4, 28, 0x23329486u, 0, 0}, // Mod interface vtable
    {0x00286530, 301, 0x55DDD320u, 0, 0}, // native GUID text parser
    {0x002864B0, 128, 0xE682F849u, 0, 0}, // native GUID hex parser
    {0x00050E70, 110, 0x70EF8E7Bu, 0, 0}, // native GUID equality
    {0x0023C370, 69, 0x22529BDFu, 0, 0}, // native narrow string construction
    {0x0023C520, 33, 0x788DA9A2u, 0, 0}, // native narrow string destruction
};
} // namespace MajestyGogAudit
