# Generated by scripts/audit_gog_qol.py; see docs/gog-qol.md.
function Assert-GogQolStock {
    param([byte[]]$Bytes)
    if ($Bytes.Length -lt 0x400) { return }
    $pe = [BitConverter]::ToUInt32($Bytes, 0x3C)
    if ($pe -gt ($Bytes.Length - 24) -or [BitConverter]::ToUInt32($Bytes, $pe + 8) -ne 0x5BBB8DB8) { return }
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        $table = $pe + 24 + [BitConverter]::ToUInt16($Bytes, $pe + 20)
        $header = [BitConverter]::ToString($sha.ComputeHash($Bytes,$table,160)).Replace('-','')
        if ($header -ne "2986FD63DAA2836FBE20521241446CDB718644BA9B1108D830B92FCED92A6DBF") { throw "GOG stock section layout differs. No files were changed." }
        $ranges = @(
            @(434679, 1069, "702BD5EFFB11107FED72A9585B25F347D23FB79E6AC1D7945F1D24D7B01E28C9"),
            @(435754, 319, "B83452842C8B486766ECC023E54D181BC39A4565D9A71CB80038B5D549B3C06A"),
            @(436079, 153, "923D086C061873437CE898E9B9E53771F06AC78418C8A3BA6B62552919B31A41"),
            @(437095, 365, "C103642F7E125C15268B5EF2B7522481F2F22AEB7B76335C6EF4E9537CE3B7C4"),
            @(2342976, 145, "B68B945A00C0703F2981FD22A3A422887DDD7EB7476F4D73E64D30DAC307A618"),
            @(152416, 108, "1D1CD3A0B283D99B6D05E27105CD65034CFCF34566EEB12BA4CE79953F3F089C"),
            @(348432, 40, "DDC77C92AEE78F7D6230D0BBADBCA5E21CE4CB989845629ABF52E9A7D184FF63"),
            @(362512, 342, "724E391A18E55480DA657800CA3EC28E3DD9BB76CBC7A35EC1697C382A8F4A2A"),
            @(348960, 465, "21BE86098C85E17E10C7F8C59C3C5C5B0BB2A5768FDB11DDAD188B7BA0750B33"),
            @(349440, 610, "D1D5C036AAD0D3B6B5683A26C7A256D03EFE7FBCFE42C32C5333DC15C30E4AD8")
        )
        foreach ($range in $ranges) {
            $actual = [BitConverter]::ToString($sha.ComputeHash($Bytes,$range[0],$range[1])).Replace('-','')
            if ($actual -ne $range[2]) { throw "GOG stock QoL lifecycle bytes differ. No files were changed." }
        }
    } finally { $sha.Dispose() }
}
