# Generated by scripts/audit_gog_qol.py; see docs/gog-qol.md.
function Assert-GogQolStock {
    param([byte[]]$Bytes)
    if ($Bytes.Length -lt 0x400) { return }
    $pe = [BitConverter]::ToUInt32($Bytes, 0x3C)
    if ($pe -gt ($Bytes.Length - 24) -or [BitConverter]::ToUInt32($Bytes, $pe + 8) -ne 0x5BBB8DB8) { return }
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        $table = $pe + 24 + [BitConverter]::ToUInt16($Bytes, $pe + 20)
        $header = [BitConverter]::ToString($sha.ComputeHash($Bytes,$table,160)).Replace('-','')
        if ($header -ne "2986FD63DAA2836FBE20521241446CDB718644BA9B1108D830B92FCED92A6DBF") { throw "GOG stock section layout differs. No files were changed." }
        $ranges = @(
            @(491440, 742, "9C33E4FB877BC42C28804CF0AEB369D7EA7BC2A153F7A44F9650B1712367402F"),
            @(492186, 301, "6DB367BAD35638D221DDE26B3FF75E07635AF80CFCFB619EC1393B5C25A1D468"),
            @(492496, 253, "2F291141D8B98CFF3C7CA55BC596DD123315E9A581FBB0497B40C5ECD436BA65"),
            @(492750, 1275, "F1C91EC158B9C85022DD20526A5C9760A51CFA6F737205779D82ED1EC22275AE"),
            @(494033, 568, "FC931F426CE8A122F6AF5770EFCA9D0B4C293C6C92D490F0C4F03A9A83A98DD3"),
            @(494607, 10, "7C209C7B944AE8F87D9BBCBEF87BEC9205732FB1296DE340C9A8528FE30555C1"),
            @(494621, 375, "8942ED8B7354991D12DEE1441B4A0F1D23B788C6E00B6942243AE0537BBADDF1"),
            @(495005, 173, "BA1D47E8BDA277A001CE37FD4B7AD7D4B68A5D209B6BA2E83126EF62FDBD6B9E"),
            @(389136, 232, "7B6FB62D2252AB06BE37541DC49B119012ECF86842BB2A2950B309652543701E"),
            @(2396160, 152, "0A717192E40AA763AF7CD2A62CE9B9DB8A653A346DB781D603DBA2380B18FCE2"),
            @(2396320, 5, "5FC155DB69ABE4DDBF3C6CDCFE0683D805109C24E5BCF05F7FB5517A21B26E74")
        )
        foreach ($range in $ranges) {
            $actual = [BitConverter]::ToString($sha.ComputeHash($Bytes,$range[0],$range[1])).Replace('-','')
            if ($actual -ne $range[2]) { throw "GOG stock QoL lifecycle bytes differ. No files were changed." }
        }
    } finally { $sha.Dispose() }
}
