# Generated by scripts/audit_gog_qol.py; see docs/gog-qol.md.
function Assert-GogQolStock {
    param([byte[]]$Bytes)
    if ($Bytes.Length -lt 0x400) { return }
    $pe = [BitConverter]::ToUInt32($Bytes, 0x3C)
    if ($pe -gt ($Bytes.Length - 24) -or [BitConverter]::ToUInt32($Bytes, $pe + 8) -ne 0x5BBB8DB8) { return }
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        $table = $pe + 24 + [BitConverter]::ToUInt16($Bytes, $pe + 20)
        $header = [BitConverter]::ToString($sha.ComputeHash($Bytes,$table,160)).Replace('-','')
        if ($header -ne "2986FD63DAA2836FBE20521241446CDB718644BA9B1108D830B92FCED92A6DBF") { throw "GOG stock section layout differs. No files were changed." }
        $ranges = @(
            @(2036640, 609, "33D0FFAB3AC59FA6FFC664D508853A6FB4F2C1C83DDD0DB1791E59C2D859DA25"),
            @(2037392, 198, "6A5B59DA87F382E684E4668FC3089B8BC138DE56AD255613A121E221BE59E16E"),
            @(2037595, 168, "A2CE4A4EE317F986536BB4FA6441B81E15EF1E569F5A80D371DCF10AE16DB021")
        )
        foreach ($range in $ranges) {
            $actual = [BitConverter]::ToString($sha.ComputeHash($Bytes,$range[0],$range[1])).Replace('-','')
            if ($actual -ne $range[2]) { throw "GOG stock QoL lifecycle bytes differ. No files were changed." }
        }
    } finally { $sha.Dispose() }
}
