"""Reproduce the fixed stock-loader guards from the pristine GOG executable."""
from pathlib import Path
import argparse
import hashlib
import json

import pefile

ROOT = Path(__file__).resolve().parents[1]
PRISTINE_SHA256 = "65c6dd32c3d873c2e320bdaa2de1b00488af85b44573fd0fd82f79a2ffd37792"
RANGES = (
    (0xEFCBB, 0xEFCF1, "last local quest scan and finalize boundary"),
    (0x119650, 0x1198B4, "recursive quest directory scanner"),
    (0x1195A0, 0x119646, "quest manifest XML load and release"),
    (0x119520, 0x1195A0, "Quest node iteration"),
    (0x119380, 0x119513, "Quest registration and native duplicate handling"),
    (0x117F60, 0x11800C, "quest lookup by native GUID key"),
    (0x136B10, 0x136BC6, "native GUID key mapping"),
    (0x113860, 0x113914, "Quest construction using stock Mod initialization"),
    (0x136C20, 0x136D4A, "GUID storage and XML document retention"),
    (0x113A30, 0x113A78, "Quest destruction"),
    (0x135CE0, 0x135D57, "base Mod destruction and XML release"),
    (0x118100, 0x118132, "quest list insertion"),
    (0x1163C0, 0x116468, "quest list node construction"),
    (0x11A940, 0x11A9AC, "quest list sentinel initialization"),
    (0x11A9B0, 0x11AA19, "quest list destruction"),
    (0x11CD90, 0x11CEA1, "quest manager destruction"),
    (0x11CEB0, 0x11D3F4, "quest manager construction"),
    (0x11D400, 0x11D46F, "quest manager lazy creation"),
    (0x11DC90, 0x11DCB7, "quest manager destruction and owner clear"),
    (0xEF027, 0xEF02C, "stock resource teardown calls quest cleanup"),
    (0xF9DA0, 0xF9EB3, "XML manifest-relative resource directory"),
    (0x286530, 0x28665D, "native GUID parsing"),
    (0x2864B0, 0x286530, "native GUID hex parser"),
    (0x23C370, 0x23C3B5, "stock string construction"),
    (0x23C520, 0x23C541, "stock string destruction"),
)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("executable", type=Path)
    args = parser.parse_args()
    raw = args.executable.read_bytes()
    if hashlib.sha256(raw).hexdigest() != PRISTINE_SHA256:
        parser.error("requires the exact pristine GOG 1.5.2.28 executable")
    data = pefile.PE(data=raw).get_memory_mapped_image()
    rows = []
    header = ['#pragma once', '#include "GogAuditedRanges.h"', '',
              '// Generated by scripts/audit_gog_quests.py; see docs/gog-workshop-quests.md.',
              'namespace MajestyGogAudit {', 'constexpr Range kWorkshopQuests[] = {']
    for start, end, label in RANGES:
        body = data[start:end]
        fingerprint = 2166136261
        for byte in body:
            fingerprint = ((fingerprint ^ byte) * 16777619) & 0xFFFFFFFF
        header.append(f'    {{0x{start:08X}, {len(body)}, 0x{fingerprint:08X}u, 0, 0}}, // {label}')
        rows.append(dict(rva=f"0x{start:X}", size=len(body), fnv1a=f"0x{fingerprint:08X}",
                         sha256=hashlib.sha256(body).hexdigest(), label=label))
    header += ['};', '} // namespace MajestyGogAudit', '']
    (ROOT / 'runtime/GogQuestAudit.h').write_text('\n'.join(header), encoding='utf-8')
    (ROOT / 'docs/gog-quest-audit.json').write_text(json.dumps(
        dict(executable_sha256=PRISTINE_SHA256, ranges=rows), indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
