"""Reproduce the fixed stock-loader guards from the pristine GOG executable."""
from pathlib import Path
import argparse
import hashlib
import json

import pefile

ROOT = Path(__file__).resolve().parents[1]
PRISTINE_SHA256 = "65c6dd32c3d873c2e320bdaa2de1b00488af85b44573fd0fd82f79a2ffd37792"
RANGES = (
    (0xEFCF1, 0xEFD1C, "startup scan arguments and call"),
    (0x139890, 0x139AF3, "recursive directory scan"),
    (0x1397E0, 0x139881, "manifest XML load and registration"),
    (0x139760, 0x1397D3, "Mod node iteration"),
    (0x139590, 0x139760, "Mod registration and installed-list insertion"),
    (0xF9DA0, 0xF9EB3, "XML manifest path and relative directory ownership"),
    (0x136E70, 0x136F1D, "Mod construction"),
    (0x136C20, 0x136D4A, "Mod initialization and XML retention"),
    (0x135CE0, 0x135D57, "Mod destruction and XML release"),
    (0x138370, 0x1383A2, "installed-list append"),
    (0x138EA0, 0x138F28, "installed-list GUID lookup"),
    (0x138D90, 0x138E8A, "stock installed and active list cleanup"),
    (0xEF068, 0xEF072, "resource teardown dispatch to mod cleanup"),
    (0x349AA0, 0x349AB6, "CRT installed-list initialization"),
    (0x31CAB0, 0x31CABA, "CRT installed-list destruction"),
    (0x136AA0, 0x136B0C, "list sentinel construction"),
    (0x1366E0, 0x136739, "list destruction"),
    (0x35B1A4, 0x35B1C0, "Mod interface vtable"),
    (0x286530, 0x28665D, "native GUID text parser"),
    (0x2864B0, 0x286530, "native GUID hex parser"),
    (0x50E70, 0x50EDE, "native GUID equality"),
    (0x23C370, 0x23C3B5, "native narrow string construction"),
    (0x23C520, 0x23C541, "native narrow string destruction"),
)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("executable", type=Path)
    args = parser.parse_args()
    raw = args.executable.read_bytes()
    if hashlib.sha256(raw).hexdigest() != PRISTINE_SHA256:
        parser.error("requires the exact pristine GOG 1.5.2.28 executable")
    data = pefile.PE(data=raw).get_memory_mapped_image()
    rows = []
    header = ['#pragma once', '#include "GogAuditedRanges.h"', '',
              '// Generated by scripts/audit_gog_standard_mods.py; see docs/gog-standard-mods.md.',
              'namespace MajestyGogAudit {', 'constexpr Range kStandardMods[] = {']
    for start, end, label in RANGES:
        body = data[start:end]
        fingerprint = 2166136261
        for byte in body:
            fingerprint = ((fingerprint ^ byte) * 16777619) & 0xFFFFFFFF
        header.append(f'    {{0x{start:08X}, {len(body)}, 0x{fingerprint:08X}u, 0, 0}}, // {label}')
        rows.append(dict(rva=f"0x{start:X}", size=len(body), fnv1a=f"0x{fingerprint:08X}",
                         sha256=hashlib.sha256(body).hexdigest(), label=label))
    header += ['};', '} // namespace MajestyGogAudit', '']
    (ROOT / 'runtime/GogStandardModAudit.h').write_text('\n'.join(header), encoding='utf-8')
    (ROOT / 'docs/gog-standard-mod-audit.json').write_text(json.dumps(
        dict(executable_sha256=PRISTINE_SHA256, ranges=rows), indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
