"""Emit an apply_patch addition for the audited x86 presenter metadata.

Offline maintainer tool only; not imported or run by the Manager. Requires
pefile/capstone and both supported, unmodified Majesty executables.
"""
import argparse
import struct

import capstone
import pefile


FUNCTIONS = {
    "Public": ((0x4962E0, 0x441), (0x496730, 0x63), (0x4B2580, 0x1C9),
               (0x4B2010, 0x10), (0x4B22C0, 0x5D)),
    "Beta": ((0x496AF0, 0x441), (0x496F40, 0x63), (0x4B2E70, 0x1C9),
             (0x4B2900, 0x10), (0x4B2BB0, 0x5D)),
    "Gog": ((0x4970A0, 0x441), (0x4974F0, 0x63), (0x4B3420, 0x1C9),
            (0x4B2EB0, 0x10), (0x4B3160, 0x5D)),
}
HELPERS = {
    "Public": (0x495D50, 0x495FC0, 0x496080, 0x4962A0, 0x496130, 0x4B2320, 0x4B1F50),
    "Beta": (0x496560, 0x4967D0, 0x496890, 0x496AB0, 0x496940, 0x4B2C10, 0x4B2840),
    "Gog": (0x496B10, 0x496D80, 0x496E40, 0x497060, 0x496EF0, 0x4B31C0, 0x4B2DF0),
}


def metadata(path, label):
    pe = pefile.PE(str(path))
    base = pe.OPTIONAL_HEADER.ImageBase
    data = pe.get_memory_mapped_image()
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    md.detail = True
    relocations = {base + entry.rva for block in getattr(pe, "DIRECTORY_ENTRY_BASERELOC", ())
                   for entry in block.entries if entry.type == 3}
    output, descriptors = [], []
    for number, (address, size) in enumerate(FUNCTIONS[label]):
        code = data[address-base:address-base+size]
        instructions = list(md.disasm(code, address))
        assert sum(i.size for i in instructions) == size, (label, number, "partial instruction")
        relocs = sorted(value-address for value in relocations if address <= value < address+size)
        canonical = bytearray(code)
        for offset in relocs:
            canonical[offset:offset+4] = bytes(4)
        fingerprint = 2166136261
        for value in canonical:
            fingerprint = ((fingerprint ^ value) * 16777619) & 0xFFFFFFFF
        branches, controls = [], []
        for ins in instructions:
            if ins.group(capstone.CS_GRP_JUMP) or ins.group(capstone.CS_GRP_CALL):
                if ins.operands[0].type != capstone.x86.X86_OP_IMM:
                    continue
                target = ins.operands[0].imm
                if address <= target < address+size:
                    continue
                assert ins.bytes[0] in (0xE8, 0xE9) and ins.size == 5, (ins.address, "external short branch")
                role = HELPERS[label].index(target)+1 if target in HELPERS[label] else 0
                branches.append((ins.address-address, target-base, role))
            for operand in ins.operands:
                if operand.type == capstone.x86.X86_OP_IMM and operand.imm in (0x1F48, 0x1F51):
                    assert ins.imm_size == 4
                    controls.append((ins.address-address+ins.imm_offset, operand.imm))
        stem = f"k{label}{number}"
        for suffix, ctype, values in (("Relocs", "std::uint32_t", relocs),
                                      ("Branches", "Branch", branches),
                                      ("Controls", "Control", controls)):
            if values:
                rendered = [f"0x{v:X}u" if isinstance(v, int) else
                            "{" + ", ".join(f"0x{x:X}u" for x in v) + "}" for v in values]
                output.append(f"constexpr {ctype} {stem}{suffix}[] = {{" + ", ".join(rendered) + "};")
        arrays = ", ".join(f"{stem}{suffix}, {len(values)}" if values else "nullptr, 0"
                           for suffix, values in (("Relocs", relocs), ("Branches", branches), ("Controls", controls)))
        descriptors.append(f"    {{0x{address-base:X}u, 0x{size:X}u, 0x{fingerprint:08X}u, {arrays}}},")
    output += [f"constexpr Code k{label}[] = {{", *descriptors, "};"]
    output += [f"constexpr std::uint32_t k{label}Helpers[] = {{" +
               ", ".join(f"0x{x-base:X}u" for x in HELPERS[label]) + "};"]
    return output


def render(public, beta, gog=None):
    return "\n".join([
        "// Generated by scripts/audit_private_recruitment.py from audited executables.",
        "#pragma once", "#include <cstdint>", "#include <cstddef>",
        "namespace MajestyPrivateRecruitment {",
        "struct Branch { std::uint32_t offset, targetRva, role; };",
        "struct Control { std::uint32_t offset, id; };",
        "struct Code {",
        "    std::uint32_t rva, size, hash;",
        "    const std::uint32_t* relocations; std::size_t relocationCount;",
        "    const Branch* branches; std::size_t branchCount;",
        "    const Control* controls; std::size_t controlCount;",
        "};", *metadata(public, "Public"), *metadata(beta, "Beta"),
        *(metadata(gog, "Gog") if gog is not None else []), "}", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("public")
    parser.add_argument("beta")
    parser.add_argument("--gog")
    args = parser.parse_args()
    print("*** Begin Patch\n*** Add File: runtime/PrivateRecruitmentProfiles.h")
    print("\n".join("+" + line for line in render(args.public, args.beta, args.gog).splitlines()))
    print("*** End Patch")
