"""Reproduce GOG QoL callee guards from the independently audited stock image."""
import argparse
import hashlib
import json
from pathlib import Path
import pefile

ROOT = Path(__file__).resolve().parents[1]
SHA256 = "65c6dd32c3d873c2e320bdaa2de1b00488af85b44573fd0fd82f79a2ffd37792"
# Hook bytes are checked separately by the owning installer/restorer. Exclude
# these exact fields from body hashes so independently reversible utilities
# coexist. No other bytes are normalized or searched at runtime.
HOOKS = ((0x4A4C0,6),(0x6ADF0,7),(0x6B760,7),(0x78E96,4),(0x79819,4),
         (0x795C9,8),(0x11DA40,7),(0x79809,6),(0x79994,9),(0x790CD,1),
         (0x1F2356,5),(0x6C138,5),(0x65443,6),(0x654E5,6),(0xD9E25,5),
         (0xDA829,5),(0x6B224,6),(0x6B369,6),(0x7C2FB,6),(0x29E32,6),(0x29E45,6))
MENU = ((0x78BB0,0x78FC7),(0x78FD0,0x79A4A))
RANGES = {
    "downloadable-quests-shortcut": MENU + ((0x77BE0,0x77F19),),
    "quest-map-drag": MENU + ((0x5FC10,0x5FCF8),(0x249C00,0x249C98),(0x249CA0,0x249CA5)),
    "unlock-all-quests": MENU + ((0x11DA40,0x11DB58),),
    "suppress-all-message-flags": ((0x4A4C0,0x4A5C5),(0x32670,0x32763)),
    "remember-game-speed": ((0x6C0F0,0x6C162),(0x64F50,0x6572C),
        (0xD9DE0,0xD9E2E),(0xDA740,0xDA84E),(0x6ADF0,0x6B408),
        (0x7C1E0,0x7C33D),(0x29CF0,0x29F28),(0xD88E0,0xD8A11)),
    "remember-camera-zoom": ((0x1F1FA0,0x1F2201),(0x1F2290,0x1F2403)),
    "lower-tracking-window": ((0x6ADF0,0x6B408),(0x6B760,0x6B8D4),
        (0x23CC40,0x23CCD1),(0x25F60,0x25FCC),(0x55D10,0x55D38),
        (0x59410,0x59566),(0x55F20,0x560F1),(0x56100,0x56362)),
}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("executable", type=Path)
    args = parser.parse_args()
    raw = args.executable.read_bytes()
    if hashlib.sha256(raw).hexdigest() != SHA256:
        parser.error("requires the pristine audited GOG 1.5.2.28 image")
    pe = pefile.PE(data=raw)
    mapped = pe.get_memory_mapped_image()
    header_sha = hashlib.sha256(b"".join(s.__pack__() for s in pe.sections)).hexdigest().upper()
    audit = {"executable_sha256": SHA256, "utilities": {}}
    for slug, ranges in RANGES.items():
        rows = []
        for start, end in ranges:
            boundaries = sorted({start, end} | {v for a,n in HOOKS for v in (a,a+n) if start < v < end})
            for a,b in zip(boundaries,boundaries[1:]):
                if any(h <= a < h+n for h,n in HOOKS):
                    continue
                rows.append(dict(rva=a, offset=pe.get_offset_from_rva(a), size=b-a,
                                 sha256=hashlib.sha256(mapped[a:b]).hexdigest().upper()))
        audit["utilities"][slug] = rows
        lines = ["# Generated by scripts/audit_gog_qol.py; see docs/gog-qol.md.",
            "function Assert-GogQolStock {", "    param([byte[]]$Bytes)",
            "    if ($Bytes.Length -lt 0x400) { return }",
            "    $pe = [BitConverter]::ToUInt32($Bytes, 0x3C)",
            "    if ($pe -gt ($Bytes.Length - 24) -or [BitConverter]::ToUInt32($Bytes, $pe + 8) -ne 0x5BBB8DB8) { return }",
            "    $sha = [Security.Cryptography.SHA256]::Create()", "    try {",
            "        $table = $pe + 24 + [BitConverter]::ToUInt16($Bytes, $pe + 20)",
            "        $header = [BitConverter]::ToString($sha.ComputeHash($Bytes,$table,160)).Replace('-','')",
            f'        if ($header -ne "{header_sha}") {{ throw "GOG stock section layout differs. No files were changed." }}',
            "        $ranges = @("]
        lines += [f'            @({r["offset"]}, {r["size"]}, "{r["sha256"]}")'+("," if i+1<len(rows) else "") for i,r in enumerate(rows)]
        lines += ["        )", "        foreach ($range in $ranges) {",
            "            $actual = [BitConverter]::ToString($sha.ComputeHash($Bytes,$range[0],$range[1])).Replace('-','')",
            '            if ($actual -ne $range[2]) { throw "GOG stock QoL lifecycle bytes differ. No files were changed." }',
            "        }", "    } finally { $sha.Dispose() }", "}", ""]
        (ROOT / "helpers" / slug / "scripts/GogStockAudit.ps1").write_text("\n".join(lines))
    (ROOT / "docs/gog-qol-audit.json").write_text(json.dumps(audit,indent=2)+"\n")

if __name__ == "__main__":
    main()
